//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shifrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Symbols
    {
        public string oldsymbol { get; set; }
        public string newsymbol { get; set; }
    }
}
